commonAnnotations:
  rafay.dev/registry-kee394k: "demo-registry"
image:
  registry: docker.io
  repository: jerseymec/nginx-portfolio
  tag: sha-879185fbe522f1dfc2230aa377cbbdf3ab26646d
  pullPolicy: Always
replicaCount: 4
containerPorts:
  http: 80
service:
  type: ClusterIP
ingress:
  enabled: true
  hostname: "nginx-demo.dev.bxdata.com"
